import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Mulish } from 'next/font/google'

import './globals.css'
import { Toaster } from '@/components/ui/toaster'

const beelova910 = localFont({
  src: './fonts/beelova910.woff',
  variable: '--font-beelova-910',
  weight: '100 900',
})

const mulish = Mulish({
  subsets: ['latin'], // Specify the subsets you need
  weight: ['400', '700'], // Include the font weights you require
  variable: '--font-mulish', // Define a CSS variable for the font
})

const preahvihear = localFont({
  src: './fonts/Preahvihear-Regular.woff',
  variable: '--font-preahvihear',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${beelova910.variable}  ${mulish.variable} ${preahvihear.variable}`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  )
}
